apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.devtools.ksp'

android {
    namespace "com.github.k1rakishou.chan.core.logger"

    compileSdk 36

    defaultConfig {
        minSdkVersion 23

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
        android {
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
        freeCompilerArgs = ["-Xstring-concat=inline"]
    }
}

dependencies {
    implementation("androidx.compose.ui:ui:${versions.compose_version}")
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${versions.kotlin_version}"
    implementation "joda-time:joda-time:${versions.joda_time}"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:${versions.kotlin_coroutines_version}"

    implementation "androidx.room:room-runtime:${versions.room_version}"
    implementation "androidx.room:room-ktx:${versions.room_version}"
    ksp "androidx.room:room-compiler:${versions.room_version}"
}