package com.github.k1rakishou.chan.utils

object RequestCodes {
  const val REPLY_NORMAL_NOTIFICATION_CLICK_REQUEST_CODE = 1
  const val REPLY_SUMMARY_NOTIFICATION_CLICK_REQUEST_CODE = 2
  const val REPLY_ALL_NOTIFICATIONS_SWIPE_REQUEST_CODE = 3
  const val LAST_PAGE_ALL_NOTIFICATIONS_CLICK_REQUEST_CODE = 4
  const val LOCAL_FILE_PICKER_LAST_SELECTION_REQUEST_CODE = 5
  const val SAVING_NOTIFICATION_REQUEST_CODE = 6
}