package com.github.k1rakishou.chan.core.di.component.activity;

import com.github.k1rakishou.chan.StartActivity;
import com.github.k1rakishou.chan.controller.ui.NavigationControllerContainerLayout;
import com.github.k1rakishou.chan.core.di.module.activity.StartActivityModule;
import com.github.k1rakishou.chan.core.di.scope.PerActivity;
import com.github.k1rakishou.chan.core.presenter.ImageReencodingPresenter;
import com.github.k1rakishou.chan.core.presenter.ImageViewerPresenter;
import com.github.k1rakishou.chan.core.presenter.ImportExportSettingsPresenter;
import com.github.k1rakishou.chan.features.bookmarks.BookmarksController;
import com.github.k1rakishou.chan.features.bookmarks.BookmarksPresenter;
import com.github.k1rakishou.chan.features.bookmarks.BookmarksSetGridModeViewWidthController;
import com.github.k1rakishou.chan.features.bookmarks.BookmarksSortingController;
import com.github.k1rakishou.chan.features.bookmarks.epoxy.BaseThreadBookmarkViewHolder;
import com.github.k1rakishou.chan.features.bookmarks.epoxy.EpoxyGridThreadBookmarkViewHolder;
import com.github.k1rakishou.chan.features.bookmarks.epoxy.EpoxyListThreadBookmarkViewHolder;
import com.github.k1rakishou.chan.features.drawer.DrawerController;
import com.github.k1rakishou.chan.features.drawer.DrawerPresenter;
import com.github.k1rakishou.chan.features.drawer.epoxy.EpoxyHistoryEntryView;
import com.github.k1rakishou.chan.features.gesture_editor.AdjustAndroid10GestureZonesController;
import com.github.k1rakishou.chan.features.gesture_editor.AdjustAndroid10GestureZonesView;
import com.github.k1rakishou.chan.features.proxies.ProxyEditorController;
import com.github.k1rakishou.chan.features.proxies.ProxySetupController;
import com.github.k1rakishou.chan.features.proxies.epoxy.EpoxyProxyView;
import com.github.k1rakishou.chan.features.search.GlobalSearchController;
import com.github.k1rakishou.chan.features.search.SearchResultsController;
import com.github.k1rakishou.chan.features.search.epoxy.EpoxySearchEndOfResultsView;
import com.github.k1rakishou.chan.features.search.epoxy.EpoxySearchErrorView;
import com.github.k1rakishou.chan.features.search.epoxy.EpoxySearchPostDividerView;
import com.github.k1rakishou.chan.features.search.epoxy.EpoxySearchPostGapView;
import com.github.k1rakishou.chan.features.search.epoxy.EpoxySearchPostView;
import com.github.k1rakishou.chan.features.search.epoxy.EpoxySearchSelectedSiteView;
import com.github.k1rakishou.chan.features.settings.MainSettingsControllerV2;
import com.github.k1rakishou.chan.features.settings.SettingsCoordinator;
import com.github.k1rakishou.chan.features.settings.epoxy.EpoxyBooleanSetting;
import com.github.k1rakishou.chan.features.settings.epoxy.EpoxyLinkSetting;
import com.github.k1rakishou.chan.features.settings.epoxy.EpoxyNoSettingsFoundView;
import com.github.k1rakishou.chan.features.settings.epoxy.EpoxySettingsGroupTitle;
import com.github.k1rakishou.chan.features.setup.AddBoardsController;
import com.github.k1rakishou.chan.features.setup.BoardSelectionController;
import com.github.k1rakishou.chan.features.setup.BoardsSetupController;
import com.github.k1rakishou.chan.features.setup.SiteSettingsController;
import com.github.k1rakishou.chan.features.setup.SitesSetupController;
import com.github.k1rakishou.chan.features.setup.epoxy.EpoxyBoardView;
import com.github.k1rakishou.chan.features.setup.epoxy.EpoxySelectableBoardView;
import com.github.k1rakishou.chan.features.setup.epoxy.selection.EpoxyBoardSelectionView;
import com.github.k1rakishou.chan.features.setup.epoxy.selection.EpoxySiteSelectionView;
import com.github.k1rakishou.chan.features.setup.epoxy.site.EpoxySiteView;
import com.github.k1rakishou.chan.ui.adapter.PostAdapter;
import com.github.k1rakishou.chan.ui.captcha.CaptchaLayout;
import com.github.k1rakishou.chan.ui.captcha.GenericWebViewAuthenticationLayout;
import com.github.k1rakishou.chan.ui.captcha.LegacyCaptchaLayout;
import com.github.k1rakishou.chan.ui.captcha.v1.CaptchaNojsLayoutV1;
import com.github.k1rakishou.chan.ui.captcha.v2.CaptchaNoJsLayoutV2;
import com.github.k1rakishou.chan.ui.cell.CardPostCell;
import com.github.k1rakishou.chan.ui.cell.PostCell;
import com.github.k1rakishou.chan.ui.cell.PostStubCell;
import com.github.k1rakishou.chan.ui.cell.ThreadStatusCell;
import com.github.k1rakishou.chan.ui.controller.AlbumDownloadController;
import com.github.k1rakishou.chan.ui.controller.AlbumViewController;
import com.github.k1rakishou.chan.ui.controller.BrowseController;
import com.github.k1rakishou.chan.ui.controller.FiltersController;
import com.github.k1rakishou.chan.ui.controller.ImageOptionsController;
import com.github.k1rakishou.chan.ui.controller.ImageReencodeOptionsController;
import com.github.k1rakishou.chan.ui.controller.ImageViewerController;
import com.github.k1rakishou.chan.ui.controller.ImageViewerGesturesSettingsController;
import com.github.k1rakishou.chan.ui.controller.ImageViewerNavigationController;
import com.github.k1rakishou.chan.ui.controller.LicensesController;
import com.github.k1rakishou.chan.ui.controller.LoadingViewController;
import com.github.k1rakishou.chan.ui.controller.LoginController;
import com.github.k1rakishou.chan.ui.controller.LogsController;
import com.github.k1rakishou.chan.ui.controller.PopupController;
import com.github.k1rakishou.chan.ui.controller.PostRepliesController;
import com.github.k1rakishou.chan.ui.controller.RemovedPostsController;
import com.github.k1rakishou.chan.ui.controller.ReportController;
import com.github.k1rakishou.chan.ui.controller.ReportProblemController;
import com.github.k1rakishou.chan.ui.controller.SaveLocationController;
import com.github.k1rakishou.chan.ui.controller.ThreadSlideController;
import com.github.k1rakishou.chan.ui.controller.ViewThreadController;
import com.github.k1rakishou.chan.ui.controller.crashlogs.ReviewCrashLogsController;
import com.github.k1rakishou.chan.ui.controller.crashlogs.ViewFullCrashLogController;
import com.github.k1rakishou.chan.ui.controller.floating_menu.FloatingListMenuController;
import com.github.k1rakishou.chan.ui.controller.navigation.BottomNavBarAwareNavigationController;
import com.github.k1rakishou.chan.ui.controller.navigation.SplitNavigationController;
import com.github.k1rakishou.chan.ui.controller.navigation.StyledToolbarNavigationController;
import com.github.k1rakishou.chan.ui.controller.settings.SettingsController;
import com.github.k1rakishou.chan.ui.controller.settings.ThemeSettingsController;
import com.github.k1rakishou.chan.ui.controller.settings.captcha.JsCaptchaCookiesEditorController;
import com.github.k1rakishou.chan.ui.controller.settings.captcha.JsCaptchaCookiesEditorLayout;
import com.github.k1rakishou.chan.ui.epoxy.EpoxyDividerView;
import com.github.k1rakishou.chan.ui.epoxy.EpoxyErrorView;
import com.github.k1rakishou.chan.ui.epoxy.EpoxyExpandableGroupView;
import com.github.k1rakishou.chan.ui.epoxy.EpoxyTextView;
import com.github.k1rakishou.chan.ui.helper.HintPopup;
import com.github.k1rakishou.chan.ui.helper.ImageOptionsHelper;
import com.github.k1rakishou.chan.ui.helper.RemovedPostsHelper;
import com.github.k1rakishou.chan.ui.layout.FilesLayout;
import com.github.k1rakishou.chan.ui.layout.FilterLayout;
import com.github.k1rakishou.chan.ui.layout.PostRepliesContainer;
import com.github.k1rakishou.chan.ui.layout.ReplyLayout;
import com.github.k1rakishou.chan.ui.layout.ReportProblemLayout;
import com.github.k1rakishou.chan.ui.layout.SearchLayout;
import com.github.k1rakishou.chan.ui.layout.SplitNavigationControllerLayout;
import com.github.k1rakishou.chan.ui.layout.ThreadLayout;
import com.github.k1rakishou.chan.ui.layout.ThreadListLayout;
import com.github.k1rakishou.chan.ui.layout.ThreadSlidingPaneLayout;
import com.github.k1rakishou.chan.ui.layout.crashlogs.ReviewCrashLogsLayout;
import com.github.k1rakishou.chan.ui.layout.crashlogs.ViewFullCrashLogLayout;
import com.github.k1rakishou.chan.ui.settings.IntegerSettingView;
import com.github.k1rakishou.chan.ui.settings.StringSettingView;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableBarButton;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableButton;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableCardView;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableCheckBox;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableChip;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableDivider;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableEditText;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableEpoxyRecyclerView;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableFloatingActionButton;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableListView;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableProgressBar;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableRadioButton;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableRecyclerView;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableScrollView;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableSlider;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableSwitchMaterial;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableTextInputLayout;
import com.github.k1rakishou.chan.ui.theme.widget.ColorizableTextView;
import com.github.k1rakishou.chan.ui.theme.widget.TouchBlockingConstraintLayout;
import com.github.k1rakishou.chan.ui.theme.widget.TouchBlockingCoordinatorLayout;
import com.github.k1rakishou.chan.ui.theme.widget.TouchBlockingFrameLayout;
import com.github.k1rakishou.chan.ui.theme.widget.TouchBlockingLinearLayout;
import com.github.k1rakishou.chan.ui.toolbar.Toolbar;
import com.github.k1rakishou.chan.ui.toolbar.ToolbarContainer;
import com.github.k1rakishou.chan.ui.view.FloatingMenu;
import com.github.k1rakishou.chan.ui.view.HidingFloatingActionButton;
import com.github.k1rakishou.chan.ui.view.LoadingBar;
import com.github.k1rakishou.chan.ui.view.MultiImageView;
import com.github.k1rakishou.chan.ui.view.PostImageThumbnailView;
import com.github.k1rakishou.chan.ui.view.ThumbnailView;
import com.github.k1rakishou.chan.ui.view.ViewContainerWithMaxSize;
import com.github.k1rakishou.chan.ui.view.bottom_menu_panel.BottomMenuPanel;
import com.github.k1rakishou.chan.ui.view.floating_menu.epoxy.EpoxyCheckableFloatingListMenuRow;
import com.github.k1rakishou.chan.ui.view.floating_menu.epoxy.EpoxyFloatingListMenuRow;
import com.github.k1rakishou.chan.ui.view.sorting.BookmarkSortingItemView;

import org.jetbrains.annotations.NotNull;

import dagger.BindsInstance;
import dagger.Subcomponent;

@PerActivity
@Subcomponent(modules = {StartActivityModule.class})
public interface StartActivityComponent {
    void inject(@NotNull AlbumDownloadController albumDownloadController);
    void inject(@NotNull AlbumViewController albumViewController);
    void inject(@NotNull BrowseController browseController);
    void inject(@NotNull DrawerController drawerController);
    void inject(@NotNull FiltersController filtersController);
    void inject(@NotNull ImageOptionsController imageOptionsController);
    void inject(@NotNull ImageReencodeOptionsController imageReencodeOptionsController);
    void inject(@NotNull ImageViewerController imageViewerController);
    void inject(@NotNull ImageViewerNavigationController imageViewerNavigationController);
    void inject(@NotNull LicensesController licensesController);
    void inject(@NotNull LoginController loginController);
    void inject(@NotNull LogsController logsController);
    void inject(@NotNull PopupController popupController);
    void inject(@NotNull PostRepliesController postRepliesController);
    void inject(@NotNull RemovedPostsController removedPostsController);
    void inject(@NotNull ReportController reportController);
    void inject(@NotNull SaveLocationController saveLocationController);
    void inject(@NotNull SitesSetupController sitesSetupController);
    void inject(@NotNull SplitNavigationController splitNavigationController);
    void inject(@NotNull StyledToolbarNavigationController styledToolbarNavigationController);
    void inject(@NotNull ThemeSettingsController themeSettingsController);
    void inject(@NotNull ThreadSlideController threadSlideController);
    void inject(@NotNull ViewThreadController viewThreadController);
    void inject(@NotNull AdjustAndroid10GestureZonesController adjustAndroid10GestureZonesController);
    void inject(@NotNull BookmarksController bookmarksController);
    void inject(@NotNull BookmarksSetGridModeViewWidthController bookmarksSetGridModeViewWidthController);
    void inject(@NotNull BookmarksSortingController bookmarksSortingController);
    void inject(@NotNull ProxyEditorController proxyEditorController);
    void inject(@NotNull ProxySetupController proxySetupController);
    void inject(@NotNull GlobalSearchController globalSearchController);
    void inject(@NotNull SearchResultsController searchResultsController);
    void inject(@NotNull AddBoardsController addBoardsController);
    void inject(@NotNull BoardsSetupController boardsSetupController);
    void inject(@NotNull MainSettingsControllerV2 mainSettingsControllerV2);
    void inject(@NotNull SiteSettingsController siteSettingsController);
    void inject(@NotNull ImageViewerGesturesSettingsController imageViewerGesturesSettingsController);
    void inject(@NotNull ReportProblemController reportProblemController);
    void inject(@NotNull ReviewCrashLogsController reviewCrashLogsController);
    void inject(@NotNull ViewFullCrashLogController viewFullCrashLogController);
    void inject(@NotNull FloatingListMenuController floatingListMenuController);
    void inject(@NotNull BottomNavBarAwareNavigationController bottomNavBarAwareNavigationController);
    void inject(@NotNull JsCaptchaCookiesEditorController jsCaptchaCookiesEditorController);
    void inject(@NotNull SettingsController settingsController);
    void inject(@NotNull LoadingViewController loadingViewController);

    void inject(@NotNull ColorizableBarButton colorizableBarButton);
    void inject(@NotNull ColorizableButton colorizableButton);
    void inject(@NotNull ColorizableCardView colorizableCardView);
    void inject(@NotNull ColorizableCheckBox colorizableCheckBox);
    void inject(@NotNull ColorizableChip colorizableChip);
    void inject(@NotNull ColorizableEditText colorizableEditText);
    void inject(@NotNull ColorizableDivider colorizableDivider);
    void inject(@NotNull ColorizableEpoxyRecyclerView colorizableEpoxyRecyclerView);
    void inject(@NotNull ColorizableFloatingActionButton colorizableFloatingActionButton);
    void inject(@NotNull ColorizableListView colorizableListView);
    void inject(@NotNull ColorizableProgressBar colorizableProgressBar);
    void inject(@NotNull ColorizableRadioButton colorizableRadioButton);
    void inject(@NotNull ColorizableRecyclerView colorizableRecyclerView);
    void inject(@NotNull ColorizableScrollView colorizableScrollView);
    void inject(@NotNull ColorizableSlider colorizableSlider);
    void inject(@NotNull ColorizableSwitchMaterial colorizableSwitchMaterial);
    void inject(@NotNull ColorizableTextInputLayout colorizableTextInputLayout);
    void inject(@NotNull ColorizableTextView colorizableTextView);

    void inject(@NotNull EpoxyGridThreadBookmarkViewHolder epoxyGridThreadBookmarkViewHolder);
    void inject(@NotNull EpoxyListThreadBookmarkViewHolder epoxyListThreadBookmarkViewHolder);
    void inject(@NotNull EpoxyHistoryEntryView epoxyHistoryEntryView);
    void inject(@NotNull EpoxyProxyView epoxyProxyView);
    void inject(@NotNull EpoxySearchEndOfResultsView epoxySearchEndOfResultsView);
    void inject(@NotNull EpoxySearchErrorView epoxySearchErrorView);
    void inject(@NotNull EpoxySearchPostDividerView epoxySearchPostDividerView);
    void inject(@NotNull EpoxySearchPostGapView epoxySearchPostGapView);
    void inject(@NotNull EpoxySearchPostView epoxySearchPostView);
    void inject(@NotNull EpoxySearchSelectedSiteView epoxySearchSelectedSiteView);
    void inject(@NotNull EpoxyBooleanSetting epoxyBooleanSetting);
    void inject(@NotNull EpoxyLinkSetting epoxyLinkSetting);
    void inject(@NotNull EpoxyNoSettingsFoundView epoxyNoSettingsFoundView);
    void inject(@NotNull EpoxySettingsGroupTitle epoxySettingsGroupTitle);
    void inject(@NotNull EpoxyBoardView epoxyBoardView);
    void inject(@NotNull EpoxySelectableBoardView epoxySelectableBoardView);
    void inject(@NotNull EpoxyBoardSelectionView epoxyBoardSelectionView);
    void inject(@NotNull EpoxySiteSelectionView epoxySiteSelectionView);
    void inject(@NotNull EpoxySiteView epoxySiteView);
    void inject(@NotNull EpoxyDividerView epoxyDividerView);
    void inject(@NotNull EpoxyErrorView epoxyErrorView);
    void inject(@NotNull EpoxyExpandableGroupView epoxyExpandableGroupView);
    void inject(@NotNull EpoxyTextView epoxyTextView);
    void inject(@NotNull EpoxyCheckableFloatingListMenuRow epoxyCheckableFloatingListMenuRow);
    void inject(@NotNull EpoxyFloatingListMenuRow epoxyFloatingListMenuRow);

    void inject(@NotNull StartActivity startActivity);
    void inject(@NotNull CaptchaNoJsLayoutV2 captchaNoJsLayoutV2);
    void inject(@NotNull CaptchaNojsLayoutV1 captchaNojsLayoutV1);
    void inject(@NotNull ThumbnailView thumbnailView);
    void inject(@NotNull PostImageThumbnailView thumbnailView);
    void inject(@NotNull MultiImageView multiImageView);
    void inject(@NotNull ThreadLayout threadLayout);
    void inject(@NotNull FilterLayout filterLayout);
    void inject(@NotNull ReplyLayout replyLayout);
    void inject(@NotNull ThreadListLayout threadListLayout);
    void inject(@NotNull ToolbarContainer toolbarContainer);
    void inject(@NotNull CardPostCell cardPostCell);
    void inject(@NotNull LegacyCaptchaLayout legacyCaptchaLayout);
    void inject(@NotNull CaptchaLayout captchaLayout);
    void inject(@NotNull FloatingMenu floatingMenu);
    void inject(@NotNull Toolbar toolbar);
    void inject(@NotNull ThreadStatusCell threadStatusCell);
    void inject(@NotNull PostCell postCell);
    void inject(@NotNull NavigationControllerContainerLayout navigationControllerContainerLayout);
    void inject(@NotNull ImportExportSettingsPresenter importExportSettingsPresenter);
    void inject(@NotNull BookmarksPresenter bookmarksPresenter);
    void inject(@NotNull BaseThreadBookmarkViewHolder baseThreadBookmarkViewHolder);
    void inject(@NotNull DrawerPresenter drawerPresenter);
    void inject(@NotNull AdjustAndroid10GestureZonesView adjustAndroid10GestureZonesView);
    void inject(@NotNull SettingsCoordinator settingsCoordinator);
    void inject(@NotNull JsCaptchaCookiesEditorLayout jsCaptchaCookiesEditorLayout);
    void inject(@NotNull ReportProblemLayout reportProblemLayout);
    void inject(@NotNull ReviewCrashLogsLayout reviewCrashLogsLayout);
    void inject(@NotNull ViewFullCrashLogLayout viewFullCrashLogLayout);
    void inject(@NotNull HidingFloatingActionButton hidingFloatingActionButton);
    void inject(@NotNull TouchBlockingConstraintLayout touchBlockingConstraintLayout);
    void inject(@NotNull TouchBlockingCoordinatorLayout touchBlockingCoordinatorLayout);
    void inject(@NotNull TouchBlockingFrameLayout touchBlockingFrameLayout);
    void inject(@NotNull TouchBlockingLinearLayout touchBlockingLinearLayout);
    void inject(@NotNull ViewContainerWithMaxSize viewContainerWithMaxSize);
    void inject(@NotNull BottomMenuPanel bottomMenuPanel);
    void inject(@NotNull BookmarkSortingItemView bookmarkSortingItemView);
    void inject(@NotNull GenericWebViewAuthenticationLayout genericWebViewAuthenticationLayout);
    void inject(@NotNull PostAdapter postAdapter);
    void inject(@NotNull RemovedPostsHelper removedPostsHelper);
    void inject(@NotNull ImageOptionsHelper imageOptionsHelper);
    void inject(@NotNull ImageReencodingPresenter imageReencodingPresenter);
    void inject(@NotNull ImageViewerPresenter imageViewerPresenter);
    void inject(@NotNull FilesLayout filesLayout);
    void inject(@NotNull LoadingBar loadingBar);
    void inject(@NotNull ThreadSlidingPaneLayout threadSlidingPaneLayout);
    void inject(@NotNull HintPopup hintPopup);
    void inject(@NotNull PostStubCell postStubCell);
    void inject(@NotNull PostRepliesContainer postRepliesContainer);
    void inject(@NotNull SearchLayout searchLayout);
    void inject(@NotNull SplitNavigationControllerLayout splitNavigationControllerLayout);
    void inject(@NotNull IntegerSettingView integerSettingView);
    void inject(@NotNull StringSettingView stringSettingView);

    void inject(@NotNull BoardSelectionController boardSelectionController);

    @Subcomponent.Builder
    interface Builder {
        @BindsInstance
        Builder startActivity(StartActivity activity);
        @BindsInstance
        Builder startActivityModule(StartActivityModule module);

        StartActivityComponent build();
    }
}
