plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-parcelize'
    id 'com.google.devtools.ksp'
    id 'org.jetbrains.kotlin.plugin.compose' version "2.0.20"
}

android {
    namespace "com.github.k1rakishou.chan"

    compileSdk 36

    defaultConfig {
        minSdkVersion 23
    }

    buildTypes {
        release {
            minifyEnabled true
        }
        debug {
            minifyEnabled false
        }
        android {
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs = ["-opt-in=kotlin.RequiresOptIn", "-Xstring-concat=inline"]
    }

    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation project(':core-common')
    implementation project(':core-logger')
    implementation project(':core-settings')

    implementation "org.jetbrains.kotlin:kotlin-stdlib:${versions.kotlin_version}"
    implementation "androidx.core:core-ktx:${versions.core_ktx}"
    implementation "androidx.appcompat:appcompat:${versions.appcompat}"
    implementation "com.google.android.material:material:${versions.material}"
    implementation "com.google.code.gson:gson:${versions.gson}"

    implementation("androidx.compose.material:material:${versions.compose_version}")

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:${versions.kotlin_coroutines_version}"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:${versions.kotlin_coroutines_version}"
    implementation "com.github.K1rakishou:Fuck-Storage-Access-Framework:${versions.fsaf}"

    implementation "com.google.dagger:dagger:${versions.dagger_version}"
    ksp("com.google.dagger:dagger-compiler:${versions.dagger_version}")

    testImplementation "junit:junit:${versions.junit}"
}