package com.github.k1rakishou.core_themes.themes

import android.graphics.Color
import com.github.k1rakishou.core_themes.ChanTheme

class Kuroneko(
  name: String = "Kuroneko",
  isLightTheme: Boolean = false,
  lightStatusBar: Boolean = true,
  lightNavBar: Boolean = true,
  accentColor: Int = Color.parseColor("#e0224e"),
  primaryColor: Int = Color.parseColor("#090909"),
  backColor: Int = Color.parseColor("#212121"),
  backColorSecondary: Int = Color.parseColor("#171717"),
  errorColor: Int = Color.parseColor("#ff4444"),
  textColorPrimary: Int = Color.parseColor("#aeaed6"),
  textColorSecondary: Int = Color.parseColor("#8c8ca1"),
  textColorHint: Int = Color.parseColor("#7b7b85"),
  postHighlightedColor: Int = Color.parseColor("#60947383"),
  postSavedReplyColor: Int = Color.parseColor("#753ecf"),
  postSubjectColor: Int = Color.parseColor("#d5a6bd"),
  postDetailsColor: Int = textColorHint,
  postNameColor: Int = Color.parseColor("#996878"),
  postInlineQuoteColor: Int = Color.parseColor("#794e94"),
  postQuoteColor: Int = Color.parseColor("#ab4d63"),
  postHighlightQuoteColor: Int = Color.parseColor("#612c38"),
  postLinkColor: Int = Color.parseColor("#ab4d7e"),
  postSpoilerColor: Int = Color.parseColor("#000000"),
  postSpoilerRevealTextColor: Int = Color.parseColor("#ffffff"),
  postUnseenLabelColor: Int = Color.parseColor("#bf3232"),
  dividerColor: Int = Color.parseColor("#1effffff"),
  bookmarkCounterNotWatchingColor: Int = Color.parseColor("#898989"),
  bookmarkCounterHasRepliesColor: Int = Color.parseColor("#ff4444"),
  bookmarkCounterNormalColor: Int = Color.parseColor("#33B5E5"),
  scrollbarTrackColor: Int = Color.parseColor("#ffbababa"),
  scrollbarThumbColorNormal: Int = Color.parseColor("#ff262626"),
  scrollbarThumbColorDragged: Int = accentColor,
) : ChanTheme(
  name = name,
  isLightTheme = isLightTheme,
  lightStatusBar = lightStatusBar,
  lightNavBar = lightNavBar,
  accentColor = accentColor,
  primaryColor = primaryColor,
  backColor = backColor,
  backColorSecondary = backColorSecondary,
  errorColor = errorColor,
  textColorPrimary = textColorPrimary,
  textColorSecondary = textColorSecondary,
  textColorHint = textColorHint,
  postHighlightedColor = postHighlightedColor,
  postSavedReplyColor = postSavedReplyColor,
  postSubjectColor = postSubjectColor,
  postDetailsColor = postDetailsColor,
  postNameColor = postNameColor,
  postInlineQuoteColor = postInlineQuoteColor,
  postQuoteColor = postQuoteColor,
  postHighlightQuoteColor = postHighlightQuoteColor,
  postLinkColor = postLinkColor,
  postSpoilerColor = postSpoilerColor,
  postSpoilerRevealTextColor = postSpoilerRevealTextColor,
  postUnseenLabelColor = postUnseenLabelColor,
  dividerColor = dividerColor,
  bookmarkCounterNotWatchingColor = bookmarkCounterNotWatchingColor,
  bookmarkCounterHasRepliesColor = bookmarkCounterHasRepliesColor,
  bookmarkCounterNormalColor = bookmarkCounterNormalColor,
  scrollbarTrackColor = scrollbarTrackColor,
  scrollbarThumbColorNormal = scrollbarThumbColorNormal,
  scrollbarThumbColorDragged = scrollbarThumbColorDragged
)