package com.github.k1rakishou.core_themes.themes

import android.graphics.Color
import com.github.k1rakishou.core_themes.ChanTheme

class Shironeko(
  name: String = "Shironeko",
  isLightTheme: Boolean = true,
  lightStatusBar: Boolean = false,
  lightNavBar: Boolean = false,
  accentColor: Int = Color.parseColor("#b01a3e"),
  primaryColor: Int = Color.parseColor("#c8c5e8"),
  backColor: Int = Color.parseColor("#EEF2FF"),
  backColorSecondary: Int = Color.parseColor("#dbd8f5"),
  errorColor: Int = Color.parseColor("#ff4444"),
  textColorPrimary: Int = Color.parseColor("#1b1b4a"),
  textColorSecondary: Int = Color.parseColor("#42427d"),
  textColorHint: Int = Color.parseColor("#5b5b82"),
  postHighlightedColor: Int = Color.parseColor("#60a3a6b5"),
  postSavedReplyColor: Int = Color.parseColor("#753ecf"),
  postSubjectColor: Int = Color.parseColor("#d15665"),
  postDetailsColor: Int = Color.parseColor("#5b5b82"),
  postNameColor: Int = Color.parseColor("#5E2C51"),
  postInlineQuoteColor: Int = Color.parseColor("#794e94"),
  postQuoteColor: Int = Color.parseColor("#ab4d63"),
  postHighlightQuoteColor: Int = Color.parseColor("#883d4f"),
  postLinkColor: Int = Color.parseColor("#ab4d7e"),
  postSpoilerColor: Int = Color.parseColor("#000000"),
  postSpoilerRevealTextColor: Int = Color.parseColor("#ffffff"),
  postUnseenLabelColor: Int = errorColor,
  dividerColor: Int = Color.parseColor("#dbdbdb"),
  bookmarkCounterNotWatchingColor: Int = Color.parseColor("#898989"),
  bookmarkCounterHasRepliesColor: Int = Color.parseColor("#ff5744"),
  bookmarkCounterNormalColor: Int = Color.parseColor("#6033e5"),
  scrollbarTrackColor: Int = Color.parseColor("#ffa0a0a0"),
  scrollbarThumbColorNormal: Int = Color.parseColor("#ff636363"),
  scrollbarThumbColorDragged: Int = accentColor,
) : ChanTheme(
  name = name,
  isLightTheme = isLightTheme,
  lightStatusBar = lightStatusBar,
  lightNavBar = lightNavBar,
  accentColor = accentColor,
  primaryColor = primaryColor,
  backColor = backColor,
  backColorSecondary = backColorSecondary,
  errorColor = errorColor,
  textColorPrimary = textColorPrimary,
  textColorSecondary = textColorSecondary,
  textColorHint = textColorHint,
  postHighlightedColor = postHighlightedColor,
  postSavedReplyColor = postSavedReplyColor,
  postSubjectColor = postSubjectColor,
  postDetailsColor = postDetailsColor,
  postNameColor = postNameColor,
  postInlineQuoteColor = postInlineQuoteColor,
  postQuoteColor = postQuoteColor,
  postHighlightQuoteColor = postHighlightQuoteColor,
  postLinkColor = postLinkColor,
  postSpoilerColor = postSpoilerColor,
  postSpoilerRevealTextColor = postSpoilerRevealTextColor,
  postUnseenLabelColor = postUnseenLabelColor,
  dividerColor = dividerColor,
  bookmarkCounterNotWatchingColor = bookmarkCounterNotWatchingColor,
  bookmarkCounterHasRepliesColor = bookmarkCounterHasRepliesColor,
  bookmarkCounterNormalColor = bookmarkCounterNormalColor,
  scrollbarTrackColor = scrollbarTrackColor,
  scrollbarThumbColorNormal = scrollbarThumbColorNormal,
  scrollbarThumbColorDragged = scrollbarThumbColorDragged
)