name: Build Setup

on:
  workflow_call:
    inputs:
      publish-type:
        required: true
        type: string  # 'beta' or 'stable'
    secrets:
      KEYSTORE:
        required: true
      KEYSTORE_PASSWORD:
        required: true
      KEY_ALIAS:
        required: true
      KEY_PASSWORD:
        required: true
      PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Check user permission
        id: check
        if: |
          github.event_name == 'push' &&
          (startsWith(github.event.head_commit.message, '[beta]') || startsWith(github.event.head_commit.message, '[stable]'))
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        if: steps.check.outputs.has-permission
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install/Upgrade pip and requests
        if: steps.check.outputs.has-permission
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Decode Keystore File
        if: steps.check.outputs.has-permission
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 -d > ${{ github.workspace }}/kurobaex.jks

      - name: Publish APK
        if: steps.check.outputs.has-permission
        run: |
          cd Kuroba
          chmod +x ./gradlew
          MSG="${{ github.event.head_commit.message }}"
          TYPE="${{ inputs.publish-type }}"

          if [[ "$TYPE" == "beta" && "$MSG" == "[beta]"* ]]; then
            echo "Publishing beta release"
            ./gradlew assembleRelease \
              -PbuildType=1 \
              -Pandroid.injected.signing.store.file=${{ github.workspace }}/kurobaex.jks \
              -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
              -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
              -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }} \
              -Dorg.gradle.jvmargs="-Xmx4096m"
            python ${{ github.workspace }}/.github/workflows/publish/main.py beta ${{ github.workspace }}
          elif [[ "$TYPE" == "stable" && "$MSG" == "[stable]"* ]]; then
            echo "Publishing stable release"
            ./gradlew assembleRelease \
              -PbuildType=0 \
              -Pandroid.injected.signing.store.file=${{ github.workspace }}/kurobaex.jks \
              -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
              -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
              -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }} \
              -Dorg.gradle.jvmargs="-Xmx4096m"
            python ${{ github.workspace }}/.github/workflows/publish/main.py stable ${{ github.workspace }}
          fi
        env:
          PAT: ${{ secrets.PAT }}
